TutorApp/core/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "examination_tasks/",
        include("examination_tasks.urls", namespace="examination_tasks"),
    ),
    path("users/", include("users.urls", namespace="users")),
    path("quizes/", include("quizes.urls", namespace="quizes")),
    path("videos/", include("videos.urls", namespace="videos")),
    path("motifs/", include("motifs.urls", namespace="motifs")),
    path("select2/", include("django_select2.urls")),
    path("courses/", include("courses.urls", namespace="courses")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]
    urlpatterns += debug_toolbar_urls()

TutorApp/quizes/urls.py
from django.urls import path

from .views.question_views import AddQuestion, QuestionReviewView
from .views.quiz_solve_views import QuizStartView, SolveQuizWizard
from .views.quiz_views import AddQuiz, QuizList

app_name = "quizes"

urlpatterns = [
    path("add/", AddQuiz.as_view(), name="add_quiz"),
    path("", QuizList.as_view(), name="quiz_list"),
    path(
        "quiz/<int:quiz_pk>/add-question/", AddQuestion.as_view(), name="add_question"
    ),
    path("quiz/<int:quiz_pk>/solve/", SolveQuizWizard.as_view(), name="solve_quiz"),
    path("quiz/<int:quiz_pk>/start/", QuizStartView.as_view(), name="quiz_start"),
    path(
        "quiz/attempt/<int:attempt_pk>/question/<int:question_number>/",
        QuestionReviewView.as_view(),
        name="question_review",
    ),
]

TutorApp/quizes/forms/question_forms.py
from django import forms
from django.forms import inlineformset_factory
from django.utils.translation import gettext_lazy as _

from ..models import Answer, Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["text", "level_type", "picture", "explanation", "explanation_picture"]
        labels = {
            "text": _("Question Content"),
            "level_type": _("Level Type"),
            "picture": _("Illustration for the question"),
            "explanation": _("Explanation To The Question"),
            "explanation_picture": _("Explanation By Illustration To The Question"),
        }


AnswerFormSet = inlineformset_factory(
    Question, Answer, fields=["text", "is_correct"], extra=4
)

TutorApp/quizes/forms/quiz_forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from ..models import Quiz


class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ["title", "section"]

    labels = {"title": _("Quiz Title"), "section": _("Subject Section")}

TutorApp/quizes/forms/quiz_wizard_forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from ..models import Quiz


class QuizStepForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super().__init__(*args, **kwargs)
        answers = question.answers.all()
        self.fields["selected_answers"] = forms.MultipleChoiceField(
            choices=[(answer.id, answer.text) for answer in answers],
            widget=forms.CheckboxSelectMultiple,
            required=False,
        )


class QuizStartForm(forms.Form):
    QUESTION_CHOICES = [
        (10, _("10 questions")),
        (20, _("20 questions")),
        (50, _("50 questions")),
        ("all", _("All questions")),
    ]

    question_count = forms.ChoiceField(
        choices=QUESTION_CHOICES,
        widget=forms.RadioSelect,
        label=_("How many questions would you like?"),
        initial=10,
    )

    def __init__(self, quiz: Quiz, *args, **kwargs):
        self.quiz = quiz
        super().__init__(*args, **kwargs)

    def clean_question_count(self) -> str:
        question_count = self.cleaned_data["question_count"]
        available_questions = self.quiz.questions.count()

        if available_questions == 0:
            raise forms.ValidationError(
                _("This quiz has no questions yet. Cannot start!")
            )

        if question_count == "all":
            return question_count

        question_count_int = int(question_count)

        if available_questions < question_count_int:
            raise forms.ValidationError(
                _(
                    "This quiz has only %(available)d question(s). "
                    "You cannot select %(requested)d."
                )
                % {"available": available_questions, "requested": question_count_int}
            )

        return question_count

TutorApp/quizes/views/question_views.py
from typing import Any, Dict, Optional

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DetailView
from users.mixins import TeacherRequiredMixin

from ..forms.question_forms import AnswerFormSet, QuestionForm
from ..models import Question, Quiz, QuizAttempt, UserAnswer


class AddQuestion(TeacherRequiredMixin, CreateView):
    model = Question
    form_class = QuestionForm
    template_name = "quizes/add_question.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)

        if self.request.POST:
            context["formset"] = AnswerFormSet(self.request.POST)
        else:
            context["formset"] = AnswerFormSet()
        return context

    def form_valid(self, form: QuestionForm) -> HttpResponse:
        formset = AnswerFormSet(self.request.POST)

        if formset.is_valid():
            self.object = form.save(commit=False)
            quiz_pk = self.kwargs["quiz_pk"]
            quiz = get_object_or_404(Quiz, pk=quiz_pk)

            self.object.quiz = quiz
            self.object.save()
            formset.instance = self.object
            formset.save()

            messages.success(self.request, _("Question has been successfully added."))

            return super().form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self) -> str:
        quiz_pk = self.kwargs["quiz_pk"]
        return reverse_lazy("quizes:add_question", kwargs={"quiz_pk": quiz_pk})


class QuestionReviewView(LoginRequiredMixin, DetailView):
    model = UserAnswer
    template_name = "quizes/question_review.html"
    context_object_name = "user_answer"

    def get_object(self, queryset: Optional[QuerySet[UserAnswer]] = None) -> UserAnswer:
        attempt_pk: int = self.kwargs["attempt_pk"]
        question_number: int = self.kwargs["question_number"]

        try:
            attempt: QuizAttempt = QuizAttempt.objects.get(
                pk=attempt_pk,
                user=self.request.user,
            )
        except QuizAttempt.DoesNotExist:
            raise Http404("There is no attempt in this quiz for this user")

        qs: QuerySet[UserAnswer] = (
            UserAnswer.objects.filter(attempt=attempt)
            .select_related("question")
            .prefetch_related(
                "selected_answers",
                "question__answers",
            )
            .order_by("question__id")
        )

        try:
            return qs[question_number - 1]
        except IndexError:
            raise Http404("There is no question in this attempt")

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)

        user_answer = self.object

        context["correct_answers"] = user_answer.question.answers.filter(
            is_correct=True
        )

        question_number = self.kwargs["question_number"]
        total_questions = user_answer.attempt.answers.count()

        context["question_number"] = question_number
        context["total_questions"] = total_questions
        context["has_previous"] = question_number > 1
        context["has_next"] = question_number < total_questions
        context["attempt_pk"] = self.kwargs["attempt_pk"]
        context["previous_number"] = question_number - 1
        context["next_number"] = question_number + 1

        return context

TutorApp/quizes/views/quiz_solve_views.py
import logging
from typing import Any, Dict, OrderedDict

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import FormView
from formtools.wizard.views import SessionWizardView

from ..forms.quiz_wizard_forms import QuizStartForm, QuizStepForm
from ..models import Question, Quiz
from ..services.solve_quiz_services import QuizSolveService

logger = logging.getLogger(__name__)


class SolveQuizWizard(LoginRequiredMixin, SessionWizardView):

    form_list = [("dummy", QuizStepForm)]
    template_name = "quizes/quiz_solve_wizard.html"

    def get_form_list(self) -> OrderedDict[str, type]:
        """
        Build dynamic form list based on quiz questions.
        """

        quiz_pk = self.kwargs["quiz_pk"]
        quiz = get_object_or_404(Quiz, pk=quiz_pk)
        question_count = self.request.GET.get("question_count", "all")

        if question_count == "all":
            questions = quiz.questions.all().order_by("?")
        else:
            try:
                count = int(question_count)
            except (ValueError, TypeError):
                logger.warning(f"Invalid question_count '{question_count}', using 10")
                count = 10
            questions = quiz.get_random_questions(count)

        if not questions:
            logger.error(f"Quiz {quiz_pk} has no questions!")
            raise ValueError(f"Quiz '{quiz.title}' has no questions.")

        form_list = [
            (f"question_{question.id}", QuizStepForm) for question in questions
        ]

        return OrderedDict(form_list)

    def done(self, form_list, **kwargs) -> HttpResponse:

        service = QuizSolveService()
        user = self.request.user

        quiz_pk = self.kwargs["quiz_pk"]
        quiz = get_object_or_404(Quiz, pk=quiz_pk)

        user_answers = []
        for step_name in self.get_form_list().keys():
            selected = self.get_cleaned_data_for_step(step_name).get(
                "selected_answers", []
            )
            selected_ids = [int(id) for id in selected]
            user_answers.append((step_name, selected_ids))

        max_score = len(user_answers)

        question_ids = [int(step_name.split("_")[1]) for step_name, _ in user_answers]
        questions = Question.objects.filter(id__in=question_ids)

        score = service.calculate_score(list(questions), user_answers)

        attempt = service.save_quiz_attempt(user, quiz, score, max_score)

        service.save_user_answers(attempt, user_answers)

        return redirect("quizes:quiz_summary", attempt_id=attempt.id)

    def get_context_data(self, form: QuizStepForm, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(form=form, **kwargs)

        current_step = self.steps.current

        question_id = int(current_step.split("_")[1])
        question = get_object_or_404(Question, pk=question_id)
        context["question"] = question
        return context


class QuizStartView(LoginRequiredMixin, FormView):
    model = Quiz
    form_class = QuizStartForm
    template_name = "quizes/quiz_solve_start.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)

        quiz_pk = self.kwargs["quiz_pk"]
        quiz = get_object_or_404(Quiz, pk=quiz_pk)
        context["quiz"] = quiz
        context["question_count"] = quiz.questions.count()

        return context

    def form_valid(self, form: QuizStartForm) -> HttpResponseRedirect:
        question_count = form.cleaned_data["question_count"]

        quiz_pk = self.kwargs["quiz_pk"]
        return redirect(
            reverse("quizes:solve_quiz", kwargs={"quiz_pk": quiz_pk})
            + f"?question_count={question_count}"
        )

TutorApp/quizes/views/quiz_views.py
from typing import Any, Dict

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, QuerySet
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, ListView
from users.mixins import TeacherRequiredMixin

from ..forms.quiz_forms import QuizForm
from ..models import Quiz, QuizAttempt


class AddQuiz(TeacherRequiredMixin, CreateView):

    model = Quiz
    form_class = QuizForm
    template_name = "quizes/add_quiz.html"
    success_url = reverse_lazy("quizes:quiz_list")

    def form_valid(self, form: QuizForm) -> HttpResponse:
        messages.success(self.request, _("Quiz created successfully!"))
        return super().form_valid(form)


class QuizList(LoginRequiredMixin, ListView):
    model = Quiz
    template_name = "quizes/quiz_list.html"
    context_object_name = "quiz_list"

    def get_queryset(self) -> QuerySet[Quiz]:
        return Quiz.objects.select_related("section").annotate(
            number_of_questions=Count("questions")
        )

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)

        quizzes = list(context["quiz_list"])

        user_attempts = QuizAttempt.objects.filter(user=self.request.user)

        last_attempts = {}

        for attempt in user_attempts:
            if attempt.quiz_id not in last_attempts:
                last_attempts[attempt.quiz_id] = attempt

        for quiz in quizzes:
            quiz.last_attempt = last_attempts.get(quiz.id)

        context["quiz_list"] = quizzes

        return context

TutorApp/templates/quizes/add_question.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
    {% trans "Add Question" %}
{% endblock %}
{% block content %}
    <div class="container">
        <h1>{% trans "Add Question to Quiz" %}</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>{% trans "Question" %}</h2>
            {{ form.as_p }}
            <h2>{% trans "Answers" %}</h2>
            {{ formset.management_form }}
            {% for answer_form in formset %}<div class="answer-form">{{ answer_form.as_p }}</div>{% endfor %}
            <button type="submit">{% trans "Save Question" %}</button>
        </form>
    </div>
{% endblock %}

TutorApp/templates/quizes/add_quiz.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block title %}
    {% trans "Add New Quiz" %}
{% endblock %}
{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for m in messages %}
                <li class="alert {% if m.tags %}alert-{{ m.tags }}{% endif %}">{{ m }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="post" class="form-container">
        {% csrf_token %}
        <h1 class="form-title">{% trans "Add New Quiz" %}</h1>
        {% if form.non_field_errors %}
            <div class="form-errors">
                {% for error in form.non_field_errors %}<div class="error-text">{{ error }}</div>{% endfor %}
            </div>
        {% endif %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
            {{ form.title|add_class:"form-input" }}
            {% if form.title.errors %}<div class="field-errors">{{ form.title.errors|striptags }}</div>{% endif %}
        </div>
        <div class="form-group">
            <label for="{{ form.section.id_for_label }}">{{ form.section.label }}</label>
            {{ form.section|add_class:"form-input" }}
            {% if form.section.errors %}<div class="field-errors">{{ form.section.errors|striptags }}</div>{% endif %}
        </div>
        <button type="submit" class="btn-submit">{% trans "Add Quiz" %}</button>
    </form>
{% endblock %}

TutorApp/templates/quizes/question_review.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for m in messages %}
                <li class="alert {% if m.tags %}alert-{{ m.tags }}{% endif %}">{{ m }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="question-review">
        <h1>
            {% blocktrans with current=question_number total=total_questions %}
            Question {{current}} of {{ total }}
        {% endblocktrans %}
        </h1>
        <p>
            {% blocktrans with points=user_answer.points_earned %}
            Points earned: {{ points }}
        {% endblocktrans %}
        </p>
        <div class="question-text">
            <p>{{ user_answer.question.text }}</p>
            {% if user_answer.question.picture %}
                <img src="{{ user_answer.question.picture.url }}"
                     alt="{% trans 'Question image' %}">
            {% endif %}
        </div>
        <div class="answers-list">
            {% for answer in user_answer.question.answers.all %}
                {% if answer in user_answer.selected_answers.all %}
                    {% if answer.is_correct %}
                        <div class="answer-correct-selected">{{ answer.text }}</div>
                    {% else %}
                        <div class="answer-incorrect-selected">{{ answer.text }}</div>
                    {% endif %}
                {% else %}
                    {% if answer.is_correct %}
                        <div class="answer-correct-non-selected">{{ answer.text }}</div>
                    {% else %}
                        <div class="answer-incorrect-non-selected">{{ answer.text }}</div>
                    {% endif %}
                {% endif %}
            {% endfor %}
            {% if user_answer.question.explanation %}
                <div class="question-explanation">
                    <h3>{% trans "Explanation" %}</h3>
                    <p>{{ user_answer.question.explanation }}</p>
                    {% if user_answer.question.explanation_picture %}
                        <img src="{{ user_answer.question.explanation_picture.url }}"
                             alt="{% trans 'Explanation image' %}">
                    {% endif %}
                </div>
            {% endif %}
            <div class="navigation-to-another-question">
                {% if has_previous %}
                    <a href="{% url 'quizes:question_review' attempt_pk=attempt_pk question_number=previous_number %}">
                        {% trans "Previous" %}
                    </a>
                {% endif %}
                {% if has_next %}
                    <a href="{% url 'quizes:question_review' attempt_pk=attempt_pk question_number=next_number %}">{% trans "Next" %}</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

TutorApp/templates/quizes/quiz_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div class="quiz-list">
        <h1>{% trans "Available Quizzes" %}</h1>
        {% for quiz in quiz_list %}
            <div class="quiz-list-info">
                <h2>{{ quiz.title }} - {{ quiz.section }}</h2>
                <p>
                    {% blocktrans with count=quiz.number_of_questions %}
                    Questions: {{ count }}
                {% endblocktrans %}
                </p>
                {% if quiz.last_attempt %}
                    <p>
                        {% blocktrans with score=quiz.last_attempt.score max=quiz.last_attempt.max_score %}
                    Last result: {{ score }}/{{ max }}
                {% endblocktrans %}
                    </p>
                {% else %}
                    <p>{% trans "Not attempted yet" %}</p>
                {% endif %}
                <a href="{% url 'quizes:quiz_start' quiz_pk=quiz.pk %}">{% trans "Start Quiz" %}</a>
            </div>
        {% empty %}
            <p>{% trans "No quizzes available" %}</p>
        {% endfor %}
    </div>
{% endblock %}

TutorApp/templates/quizes/quiz_solve_wizard.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
    {% trans "Solve Quiz" %}
{% endblock %}
{% block content %}
    <div class="container">
        {# Progress #}
        <p>{% trans "Question" %} {{ wizard.steps.step1 }}/{{ wizard.steps.count }}</p>
        {# Pytanie #}
        <h2>{{ question.text }}</h2>
        {% if question.picture %}<img src="{{ question.picture.url }}" alt="Question image">{% endif %}
        {# Formularz #}
        <form method="post">
            {% csrf_token %}
            {{ wizard.management_form }}
            <h3>{% trans "Select answers:" %}</h3>
            {{ form.as_p }}
            {% if wizard.steps.prev %}
                <button type="submit" name="wizard_goto_step" value="{{ wizard.steps.prev }}">{% trans "Previous" %}</button>
            {% endif %}
            <button type="submit">
                {% if wizard.steps.last %}
                    {% trans "Finish" %}
                {% else %}
                    {% trans "Next" %}
                {% endif %}
            </button>
        </form>
    </div>
{% endblock %}